<?php
/**
 * @file
 * Adding an Archive.org videos handler to Video Embed Field.
 *
 * @see video_embed_field.api.php for more documentation
 */
 
 /**
 * Implements hook_video_embed_handler_info().
 */
 function video_embed_archive_video_embed_handler_info() {
  $handlers = array();
  
  $handlers['archive'] = array(
    'title' => 'Archive.org Video',
    'function' => 'video_embed_archive_handle_video',
    //'thumbnail_function' => 'video_embed_archive_handle_thumbnail',
    'thumbnail_default' => backdrop_get_path('module', 'video_embed_archive') . '/img/archive.png',
    'form' => 'video_embed_archive_form',
    'form_validate' => 'video_embed_field_handler_archive_form_validate',
    'domains' => array(
      'archive.org',
    ),
    'defaults' => array(
      'width' => 640,
      'height' => 480,
    ),
  );
  
  return $handlers;
}

/**
 * Defines the form elements for the Archive videos configuration form.
 *
 * @param array $defaults
 *   The form default values.
 *
 * @return array
 *   The provider settings form array.
 */
function video_embed_archive_form($defaults) {
  $form = array();

  $form['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Player Width'),
    '#description' => t('The width of the player.'),
    '#default_value' => $defaults['width'],
  );

  $form['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Player Height'),
    '#description' => t('The height of the player.'),
    '#default_value' => $defaults['height'],
  );

  $form['class'] = array(
    '#type' => 'textfield',
    '#title' => t('Player CSS class'),
    '#description' => t('CSS class to add to the player'),
    '#default_value' => $defaults['class'],
  );

  return $form;
}

/**
 * Validates the form elements for the Archive video configuration form.
 *
 * @param array $element
 *   The form element to validate.
 * @param array $form_state
 *   The form to validate state.
 * @param array $form
 *   The form to validate structure.
 */
function video_embed_field_handler_archive_form_validate($element, &$form_state, $form) {
  video_embed_field_validate_dimensions($element);
}

/**
 * Handler for Archive videos.
 *
 * @param string $url
 *   The video URL.
 * @param array $settings
 *   The settings array.
 *
 * @return string|bool
 *   The video iframe, or FALSE in case the ID can't be retrieved from the URL.
 */
function video_embed_archive_handle_video($url, $settings) {
  $id = _video_embed_archive_get_video_id($url);

  if ($id) {
    // Our embed code.
    $embed='<iframe class="@class" src="//archive.org/embed/!id" width="@width" height="@height" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe> ';
    // Use format_string to replace our placeholders with the settings values.
    $embed = format_string($embed, array(
      '!id' => $id,
      '@width' => $settings['width'],
      '@height' => $settings['height'],
      '@class' => $settings['class'],
    ));

    $video = array(
      '#markup' => $embed,
    );
    return $video;
  }

  return FALSE;
}

/**
 * Retrieve information about the thumbnail for a given url
 * @param $url - the url of the video as entered by the user
 * @return an array with the keys:
 *   'id' => an id for the video which is unique to your provider, used for naming the cached thumbnail file
 *   'url' => the url to retrieve the thumbnail from
 */
function video_embed_archive_handle_thumbnail($url) {
  $id = _video_embed_archive_get_video_id($url);
  
  return array(
    'id' => $id,
    'url' => 'https://archive.org/embed/services/img/' . $id . '',
  );
}


/**
 * Helper function to take an archive video url and return its id.
 *
 * @param string $url
 *   This is string witch user input into video field.
 *
 * @return string|bool
 *   Return FALSE if fails to get id using regexp on user input string.
 */
function _video_embed_archive_get_video_id($url) {
  $output = FALSE;
  $url = check_plain($url);
  // Parse_url is an easy way to break a url into its components.
  $matches = array();
  $url = preg_replace('/\?.*/', '', $url);
  // Grab id of archive_video to get thumbnail for it and construct proper
  // iframe.
  preg_match('/archive\.org\/details\/(.*)[\/]?/', $url, $matches);

  if ($matches && !empty($matches[1])) {
    // If url was with '/' symbol, clear it.
    $output = rtrim($matches[1], '/');
  }
  return $output;
}